const fs = require('fs');
const path = require('path');

function parseDotEnv(text) {
    const out = {};
    const lines = String(text || '').split(/\r?\n/);
    for (const rawLine of lines) {
        const line = rawLine.trim();
        if (!line || line.startsWith('#')) continue;
        const idx = line.indexOf('=');
        if (idx <= 0) continue;
        const key = line.slice(0, idx).trim();
        let value = line.slice(idx + 1).trim();
        if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
            value = value.slice(1, -1);
        }
        out[key] = value;
    }
    return out;
}

function parseModelList(raw, fallback) {
    if (!raw) return fallback;
    return String(raw)
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean)
        .slice(0, 3);
}

function buildConfig(env) {
    const openAiModels = parseModelList(env.OPENAI_MODELS, [
        'o3',
        'o4-mini',
        'gpt-4.1-mini'
    ]);

    const geminiModels = parseModelList(env.GEMINI_MODELS, [
        'gemini-2.5-pro',
        'gemini-2.5-flash',
        'gemini-2.0-flash'
    ]);

    return {
        generatedAt: new Date().toISOString(),
        providers: {
            'openai-compatible': {
                apiKey: env.OPENAI_API_KEY || '',
                baseUrl: env.OPENAI_BASE_URL || 'https://api.openai.com/v1',
                models: openAiModels
            },
            gemini: {
                apiKey: env.GEMINI_API_KEY || '',
                baseUrl: env.GEMINI_BASE_URL || 'https://generativelanguage.googleapis.com/v1beta/openai',
                models: geminiModels
            }
        }
    };
}

function main() {
    const root = path.resolve(__dirname, '..', '..');
    const envPath = path.join(root, '.env');
    if (!fs.existsSync(envPath)) {
        throw new Error(`.env not found at ${envPath}`);
    }

    const envRaw = fs.readFileSync(envPath, 'utf8');
    const env = parseDotEnv(envRaw);
    const config = buildConfig(env);

    const outPath = path.join(root, 'assets', 'js', 'translator.runtime-config.js');
    const payload = [
        '// Auto-generated by scripts/translation/sync_translator_runtime_config.js',
        '// Do not commit this file. It contains runtime keys from .env.',
        `window.TRANSLATOR_RUNTIME_CONFIG = ${JSON.stringify(config, null, 2)};`,
        ''
    ].join('\n');

    fs.writeFileSync(outPath, payload, 'utf8');

    const openAiEnabled = Boolean(config.providers['openai-compatible'].apiKey);
    const geminiEnabled = Boolean(config.providers.gemini.apiKey);

    console.log(JSON.stringify({
        ok: true,
        outPath,
        providers: {
            openai: { enabled: openAiEnabled, models: config.providers['openai-compatible'].models },
            gemini: { enabled: geminiEnabled, models: config.providers.gemini.models }
        }
    }, null, 2));
}

if (require.main === module) {
    try {
        main();
    } catch (err) {
        console.error(err && err.stack ? err.stack : String(err));
        process.exit(1);
    }
}
